server:  port: 8011
  servlet.session.timeout: 10
  tomcat:    uri-encoding: UTF-8spring:
  datasource:    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false  jpa:    hibernate:      ddl-auto: update    show-sql: true

hibernate.dialect: org.hibernate.dialect.MariaDBDialect
hibernate.show_sql: true
hibernate.format_sql: true
hibernate.hbm2ddl.auto: update
#entitymanager.packagesToScan: 
#启用shutdown#禁用密码验证endpoints.shutdown.sensitive=falsemanagement:#  server:#    servlet:#      context-path: /manager#    address: #    port: 8012  endpoint:    shutdown:      enabled: true