server:
  port: 8080
  http2:
    enabled: true
  servlet:
#    path: /
    session:
      timeout: 10
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: boot2
  jackson:
    time-zone: Asia/Shanghai
  data:
    elasticsearch:
      repositories:
        enabled: false
  elasticsearch:
    uris:
    - 192.168.1.8:9200
#  datasource:
#    username: root
#    password: 123456
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#entitymanager.packagesToScan:
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: tech.dhjt.boot3.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
  
#启用shutdown
#禁用密码验证endpoints.shutdown.sensitive=false
management:
#  server:
#    servlet:
#      context-path: /manager
#    address:
#    port: 8012
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    health: ""
    web:
      exposure:
        include:
        - "*"
  metrics:
    tags:
      application: ${spring.application.name}

